config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'search', to: 'search#search'
  get 'users/signup'
  get 'users/new_user'
  get 'urls/new'
  get 'urls/logout'
  get 'urls/short_to_long'
  get 'domains/new'
  get 'conversions/index'

  post 'users/username_available'
  post 'users/signup_entry'
  post 'users/login'
  post 'urls/long_to_short'
  post 'domains/create_domain'

  root 'users#new_user'

  require 'sidekiq/web'	
  get '*path' => redirect('/')
mount Sidekiq::Web, :at => '/sidekiq'
end

app/models/user.rb
class User < ApplicationRecord
  require 'digest/md5'

  validates :username, :password ,:email ,:name ,presence: true
=begin
login using given values
=end
  def self.login_using_credentials(login_params)
    md5_password = Digest::MD5.hexdigest(login_params[:password])
    if User.find_by(username: login_params[:username] , password: md5_password)
      return "logged in"
    else
      return "wrong username or password"
    end
  end 
=begin
signup using given values
=end
  def self.signup_using_credentials(signup_params)
    md5_password = Digest::MD5.hexdigest(signup_params[:password])
    users = User.create({:username => signup_params[:username] , :password => md5_password , :email => signup_params[:email] , :name => signup_params[:fullname]})
  end

=begin
check if username is available
=end
  def self.check_username_available(signup_params)
    if User.find_by(username: signup_params[:username])
      return false
    end
    return true
  end
=begin
check if email is available
=end
  def self.check_email_available(signup_params)
    if User.find_by(email: signup_params[:email])
      return false
    end
    return true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  require 'time'
  before_action :is_session_over_no, only: [:new_user, :signup]

=begin
starting pasge of the app , displays login page
=end
  def new_user
  end
=begin
signup page
=end
  def signup
  end
=begin
called when user clicks submit button on login form
=end
  def login
    if check_if_empty(login_params) == true
      flash.now[:error] = "Field cannot be empty"
      render users_new_user_path
      return
    end
    login_status = User.login_using_credentials(login_params)
    if login_status == "wrong username or password"
      flash.now[:error] = "Wrong username or password. Try Again"
      render users_new_user_path
      return
    elsif login_status == "logged in"
      session[:user] = "yes"
      session[:time] = Time.now
      redirect_to urls_new_path
      return
    end
  end
=begin
called when user clicks submit button on signup page
=end
  def signup_entry
    if check_if_empty(signup_params) == true
      flash.now[:error] = "empty field not allowed"
      render users_signup_path
      return
    end
    if User.check_username_available(signup_params) == false
      flash.now[:error] = "Username not available"
      render users_signup_path
      return
    end
    if User.check_email_available(signup_params) == false
      flash.now[:error] = "Email alredy registered"
      render users_signup_path
      return
    end
    if check_password_match(signup_params) == false
      flash.now[:error] = "password dont match"
      render users_signup_path
      return
    end
    User.signup_using_credentials(signup_params)
    redirect_to users_new_user_path
  end

  private
  def login_params
    params.permit(:username, :password)
  end

  def signup_params
    params.permit(:username , :password , :email , :fullname , :confirm_password)
  end
    
end

app/helpers/users_helper.rb
module UsersHelper
require 'digest/md5'
=begin
checks fields if they are empty
=end
  def check_if_empty(allowed_params) 
    for i in allowed_params.keys
      if allowed_params[i] == ""
        return true
      end
    end
    return false
  end

=begin
password match in signup 
=end
  def check_password_match(signup_params)
    md5_password = Digest::MD5.hexdigest(signup_params[:password])
    md5_confirm_password = Digest::MD5.hexdigest(signup_params[:confirm_password])

    if md5_password == md5_confirm_password
      return true
    end
      return false
  end

  
end

app/views/users/new_user.html.erb
<%= form_with url: users_login_path do |form| %>

  <h1>
    <center>
        Url Shortner
    </center>
  </h1>
  <!-- <p>
    <% if @a == 5 %>
      <%= javascript_tag "alert('hello welcome')" %>
    <% end %>
  </p> -->
  <p>
    <center>
      <%= form.label :username %>
      <%= form.text_field :username %><br><br>

      <%= form.label :password %>
      <%= form.password_field :password %><br><br>
    
      <%= form.submit 'Login'%><br><br>
      <%= link_to 'Signup', users_signup_path %><br><br>
      <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </center>
  </p>
  
<% end %>

app/views/users/signup.html.erb
  <h1>
    <center>
        SignUp<br><br>
    </center>    
  </h1>
  <!-- <p>
    <% if @a == 5 %>
      <%= javascript_tag "alert('hello welcome')" %>
    <% end %>
  </p> -->
  <!-- <%= form_with url: users_username_available_path do |form| %>

  <%= form.submit 'Check_Available' %>
  <%= form.label :username %><br><br>
  <% end %> -->
  <%= form_with url: users_signup_entry_path do |form| %>
  <p>
  	<center>
      <%= form.label :username %>
      <%= form.text_field :username %><br><br>

  		<%= form.label :fullname %>
    	<%= form.text_field :fullname %><br><br>

    	<%= form.label :email %>
    	<%= form.text_field :email %><br><br>

    	<%= form.label :password %>
    	<%= form.password_field :password %><br><br>

      <%= form.label :confirm_password %>
      <%= form.password_field :confirm_password %><br><br>

    	<%= form.submit 'signup' %>

      <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>

    </center>
  </p>
     
  
  <%= link_to 'back', users_new_user_path %>
<% end %>